name: Deploy article

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2 
      with:
        node-version: '16'
    - name: Build app
      run: |
        cd src/
        npm install
        npm run build-export
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated publish
        branch: main